apiVersion: v1
kind: Pod
metadata:
  name: copy-tiles-$BUILD_ID
  labels:
    app: copy-tiles-$BUILD_ID
spec:
  containers:
  - name: copy-tiles-$BUILD_ID
    image: alpine
    command: ["cp"]
    args: ["-f", "/data/worker/data/tiles.mbtiles", "/data/tileserver/tiles.mbtiles" ]
    volumeMounts:
    - name: copy-tiles-$BUILD_ID-nfs-volume
      mountPath: /data/worker
    - name: tileserver-$BUILD_ID-nfs-volume
      mountPath: /data/tileserver
  restartPolicy: Never
  volumes:
  - name: copy-tiles-$BUILD_ID-nfs-volume
    persistentVolumeClaim:
      claimName: brigade-worker-$BUILD_ID
  - name: tileserver-$BUILD_ID-nfs-volume
    persistentVolumeClaim:
      claimName: nfs