apiVersion: v1
kind: Pod
metadata:
  name: copy-tiles-$BUILD_ID
  labels:
    app: copy-tiles-$BUILD_ID
spec:
  containers:
  - name: copy-tiles-$BUILD_ID
    image: alpine
    command: [cp]
    args: ["-f", "/data/$PVC_ID/data/tiles.mbtiles", "/data/tileserver/tiles.mbtiles" ]
    volumeMounts:
    - name: copy-tiles-$BUILD_ID-nfs-volume
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: copy-tiles-$BUILD_ID-nfs-volume
    nfs:
      server: nfs-server-nfs-server-provisioner.default.svc.cluster.local
      path: /
