kind: Service
apiVersion: v1
metadata:
  name: tileserver
  labels:
    app: tileserver
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
  selector:
    app: tileserver
    version: "$VERSION"