#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: tileserver-pv
#spec:
#  accessModes:
#  - ReadWriteMany
#  capacity:
#    storage: 5Gi
#  nfs:
#    path: /export/tileserver
#    server: nfs-server-nfs-server-provisioner.default.svc.cluster.local
#  storageClassName: nfs
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: tileserver-claim
#spec:
#  accessModes:
#    - ReadWriteMany
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: nfs
#  volumeName: tileserver-pv
#---
apiVersion: v1
kind: Pod
metadata:
  name: tileserver
  labels:
    app: tileserver
spec:
  containers:
  - name: tileserver
    image: klokantech/tileserver-gl
    ports:
    - containerPort: 80
    volumeMounts:
    - name: tileserver-volume
      mountPath: /data
  volumes:
  - name: tileserver-volume
    nfs:
      server: nfs-server-nfs-server-provisioner.default.svc.cluster.local
      path: /
  #- name: tileserver-volume
  #  persistentVolumeClaim:
  #    claimName: tileserver-claim